/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\sirar\Documents\ninProgs\NGBC-game\game feature ideas\color background\MapSprites.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapWidth 20
#define MapHeight 18
#define MapBank 0

#define Map MapPLN0
extern unsigned char MapPLN0[];
extern unsigned char MapPLN1[];

/* End of MAP.H */
