/*

 MAPSPRITEST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define MapSpritesBank 0


/* Gameboy Color palette 0 */
#define MapSpritesCGBPal0c0 32767
#define MapSpritesCGBPal0c1 8935
#define MapSpritesCGBPal0c2 6596
#define MapSpritesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define MapSpritesCGBPal1c0 32767
#define MapSpritesCGBPal1c1 31664
#define MapSpritesCGBPal1c2 32640
#define MapSpritesCGBPal1c3 32165

/* Gameboy Color palette 2 */
#define MapSpritesCGBPal2c0 32767
#define MapSpritesCGBPal2c1 26425
#define MapSpritesCGBPal2c2 19026
#define MapSpritesCGBPal2c3 13741

/* Gameboy Color palette 3 */
#define MapSpritesCGBPal3c0 32767
#define MapSpritesCGBPal3c1 340
#define MapSpritesCGBPal3c2 1264
#define MapSpritesCGBPal3c3 1197

/* CGBpalette entries. */
extern unsigned char MapSpritesCGB[];
/* Start of tile array. */
extern unsigned char MapSprites[];

/* End of MAPSPRITEST.H */
