/*

 KEYBOARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\sirar\Documents\ninProgs\NGBC-game\game feature ideas\screen keyboard\KeyTitles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define KeyboardWidth 20
#define KeyboardHeight 18
#define KeyboardBank 0

extern unsigned char Keyboard[];

/* End of KEYBOARD.H */
