/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Face[] =
{
  0x7E,0x7E,0x81,0xFF,0xA5,0xFF,0xE5,0xBF,
  0xFD,0xA7,0xFF,0x81,0x7E,0x42,0x3C,0x3C,

  0x7E,0x7E,0x81,0xFF,0xA5,0xFF,0xA5,0xFF,
  0xC1,0xBF,0xFF,0x81,0x7E,0x42,0x3C,0x3C
};

/* End of EXPORT.C */
