/*

 BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 60
   Tile set      : C:\Users\sirar\Documents\ninProgs\NGBC-game\src\BGTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BGWidth 20
#define BGHeight 60
#define BGBank 0

#define BG BGPLN0
extern unsigned char BGPLN0[];
extern unsigned char BGPLN1[];
extern unsigned char BGPLN0Start[];
extern unsigned char BGPLN1Start[];

/* End of BG.H */
