/*

 BGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 30

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BGTilesBank 0

/* Gameboy Color palette 0 */
#define BGTilesCGBPal0c0 17969
#define BGTilesCGBPal0c1 23254
#define BGTilesCGBPal0c2 27482
#define BGTilesCGBPal0c3 20086

/* Gameboy Color palette 1 */
#define BGTilesCGBPal1c0 13741
#define BGTilesCGBPal1c1 19026
#define BGTilesCGBPal1c2 15852
#define BGTilesCGBPal1c3 22195

/* Gameboy Color palette 2 */
#define BGTilesCGBPal2c0 29354
#define BGTilesCGBPal2c1 2383
#define BGTilesCGBPal2c2 9503
#define BGTilesCGBPal2c3 32767

/* Gameboy Color palette 3 */
#define BGTilesCGBPal3c0 6076
#define BGTilesCGBPal3c1 2480
#define BGTilesCGBPal3c2 14271
#define BGTilesCGBPal3c3 6907

/* Gameboy Color palette 4 */
#define BGTilesCGBPal4c0 1099
#define BGTilesCGBPal4c1 8935
#define BGTilesCGBPal4c2 6596
#define BGTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BGTilesCGBPal5c0 18397
#define BGTilesCGBPal5c1 925
#define BGTilesCGBPal5c2 726
#define BGTilesCGBPal5c3 1189

/* CGBpalette entries. */
extern unsigned char BGTilesCGB[];
/* Start of tile array. */
extern unsigned char BGTiles[];

/* End of BGTILES.H */
