/*

 BLOCKSPRITEBLUE3.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BlockSpriteBlue3Bank 0

/* Super Gameboy palette 0 */
#define BlockSpriteBlue3SGBPal0c0 6076
#define BlockSpriteBlue3SGBPal0c1 8935
#define BlockSpriteBlue3SGBPal0c2 6596
#define BlockSpriteBlue3SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BlockSpriteBlue3SGBPal1c0 6076
#define BlockSpriteBlue3SGBPal1c1 8935
#define BlockSpriteBlue3SGBPal1c2 6596
#define BlockSpriteBlue3SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BlockSpriteBlue3SGBPal2c0 6076
#define BlockSpriteBlue3SGBPal2c1 8935
#define BlockSpriteBlue3SGBPal2c2 6596
#define BlockSpriteBlue3SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BlockSpriteBlue3SGBPal3c0 6076
#define BlockSpriteBlue3SGBPal3c1 8935
#define BlockSpriteBlue3SGBPal3c2 6596
#define BlockSpriteBlue3SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BlockSpriteBlue3CGBPal0c0 32767
#define BlockSpriteBlue3CGBPal0c1 0
#define BlockSpriteBlue3CGBPal0c2 19225
#define BlockSpriteBlue3CGBPal0c3 22118

/* Gameboy Color palette 1 */
#define BlockSpriteBlue3CGBPal1c0 32767
#define BlockSpriteBlue3CGBPal1c1 0
#define BlockSpriteBlue3CGBPal1c2 19225
#define BlockSpriteBlue3CGBPal1c3 8870

/* Gameboy Color palette 2 */
#define BlockSpriteBlue3CGBPal2c0 32767
#define BlockSpriteBlue3CGBPal2c1 0
#define BlockSpriteBlue3CGBPal2c2 19225
#define BlockSpriteBlue3CGBPal2c3 6357

/* Gameboy Color palette 3 */
#define BlockSpriteBlue3CGBPal3c0 6076
#define BlockSpriteBlue3CGBPal3c1 8935
#define BlockSpriteBlue3CGBPal3c2 6596
#define BlockSpriteBlue3CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BlockSpriteBlue3CGBPal4c0 6076
#define BlockSpriteBlue3CGBPal4c1 8935
#define BlockSpriteBlue3CGBPal4c2 6596
#define BlockSpriteBlue3CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BlockSpriteBlue3CGBPal5c0 6076
#define BlockSpriteBlue3CGBPal5c1 8935
#define BlockSpriteBlue3CGBPal5c2 6596
#define BlockSpriteBlue3CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BlockSpriteBlue3CGBPal6c0 6076
#define BlockSpriteBlue3CGBPal6c1 8935
#define BlockSpriteBlue3CGBPal6c2 6596
#define BlockSpriteBlue3CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BlockSpriteBlue3CGBPal7c0 6076
#define BlockSpriteBlue3CGBPal7c1 8935
#define BlockSpriteBlue3CGBPal7c2 6596
#define BlockSpriteBlue3CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BlockSpriteBlue3CGB[];
/* Start of tile array. */
extern unsigned char BlockSpriteBlue3[];

/* End of BLOCKSPRITEBLUE3.H */
