/*

 BLOCKSPRITEBLUE2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BlockSpriteBlueBank 0

/* Super Gameboy palette 0 */
#define BlockSpriteBlueSGBPal0c0 6076
#define BlockSpriteBlueSGBPal0c1 8935
#define BlockSpriteBlueSGBPal0c2 6596
#define BlockSpriteBlueSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BlockSpriteBlueSGBPal1c0 6076
#define BlockSpriteBlueSGBPal1c1 8935
#define BlockSpriteBlueSGBPal1c2 6596
#define BlockSpriteBlueSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BlockSpriteBlueSGBPal2c0 6076
#define BlockSpriteBlueSGBPal2c1 8935
#define BlockSpriteBlueSGBPal2c2 6596
#define BlockSpriteBlueSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BlockSpriteBlueSGBPal3c0 6076
#define BlockSpriteBlueSGBPal3c1 8935
#define BlockSpriteBlueSGBPal3c2 6596
#define BlockSpriteBlueSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BlockSpriteBlueCGBPal0c0 32767
#define BlockSpriteBlueCGBPal0c1 0
#define BlockSpriteBlueCGBPal0c2 19225
#define BlockSpriteBlueCGBPal0c3 22118

/* Gameboy Color palette 1 */
#define BlockSpriteBlueCGBPal1c0 6076
#define BlockSpriteBlueCGBPal1c1 8935
#define BlockSpriteBlueCGBPal1c2 6596
#define BlockSpriteBlueCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BlockSpriteBlueCGBPal2c0 6076
#define BlockSpriteBlueCGBPal2c1 8935
#define BlockSpriteBlueCGBPal2c2 6596
#define BlockSpriteBlueCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BlockSpriteBlueCGBPal3c0 6076
#define BlockSpriteBlueCGBPal3c1 8935
#define BlockSpriteBlueCGBPal3c2 6596
#define BlockSpriteBlueCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BlockSpriteBlueCGBPal4c0 6076
#define BlockSpriteBlueCGBPal4c1 8935
#define BlockSpriteBlueCGBPal4c2 6596
#define BlockSpriteBlueCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BlockSpriteBlueCGBPal5c0 6076
#define BlockSpriteBlueCGBPal5c1 8935
#define BlockSpriteBlueCGBPal5c2 6596
#define BlockSpriteBlueCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BlockSpriteBlueCGBPal6c0 6076
#define BlockSpriteBlueCGBPal6c1 8935
#define BlockSpriteBlueCGBPal6c2 6596
#define BlockSpriteBlueCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BlockSpriteBlueCGBPal7c0 6076
#define BlockSpriteBlueCGBPal7c1 8935
#define BlockSpriteBlueCGBPal7c2 6596
#define BlockSpriteBlueCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BlockSpriteBlueCGB[];
/* Start of tile array. */
extern unsigned char BlockSpriteBlue[];

/* End of BLOCKSPRITEBLUE2.H */
