/*

 ROPE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define RopeBank 0
/* Gameboy Color palette 0 */
#define RopeCGBPal0c0 12316
#define RopeCGBPal0c1 6076
#define RopeCGBPal0c2 15855
#define RopeCGBPal0c3 0

/* CGBpalette entries. */
extern unsigned char RopeCGB[];
/* Start of tile array. */
extern unsigned char Rope[];

/* End of ROPE.H */
